### ISSUE TITLE
Outliers

### ISSUE THREAD

**Issue by Kydoimos97** [Kydoimos97/CapstoneMSBA2020#11]
We need someone to go over and document all outliers and decide if they should be removed or included in the final data set.

![image](https://user-images.githubusercontent.com/63725110/107625094-0cd1f280-6c19-11eb-9614-86316ddd71d2.png)

**Comment by timgain** [comment]
# Outliers in Sales
```{r}

##choose explanatory variables
x.mcd=covMcd(df$Sales, alpha=.5) ##Run MCD

# creates a new data set where 0, 1 outlier scores are in the first column (0=outlier and 1=inlier)
sales.new <- data.frame(x.mcd$mcd.wt,df)

##Subset data after removing outliers and the first column
sales.subset <- new[-which(x.mcd$mcd.wt == 0),-1 ]

sum(x.mcd$mcd.wt == 0) # counts number of outliers (225,925 Sales outliers)
sum(x.mcd$mcd.wt == 1) # counts number of inliers (1,126,199 Sales inliers)

summary(sales.subset$Sales)  # Sales outliers begin over 5.93
IQR(sales.subset$Sales)
str(sales.subset)
ecdf(df$Sales)(5.93)  # Sales=5.93 is in the 0.832911 percentile

ggplot(sales.subset,aes(Sales)) + geom_histogram() + labs(title="Distribution of Sales After Removing Sales Outliers", x="Sales ($)", y="Count") + scale_x_continuous(labels = comma) + scale_y_continuous(labels = comma) + theme_minimal()

ggplot(sales.subset,aes(Sales)) + geom_boxplot()

## now run linear regression without outliers
#summary(sales.subset.reg <- lm(Sales~., data = sales.subset))  # can't run vector 6.5 GB
```

**Comment by timgain** [comment]
Since the data is right-skewed, a normal 1.5*IQR doesn't really work to detect outliers.  Running the Minimum Covariance Determinant (MCD) specifically on the Sales variable comes up with a maximum non-outlier Sales amount of $5.93 which is in the 83rd percentile of the full dataset.  Anything above that amount would be considered an outlier.  Removing outliers above that amount cuts out almost 226,000 data points and still leaves us with 1.1M rows.

When viewing the summary of the data subset above, it shows the max Quantity Sold as being 59.  I looked further into that and noticed there were several sales of item -12066 (Tootsie Rolls) that were sold at $0.10 each.  As a result, I didn't feel that data was incorrect and so left it alone.

I tried running the same MCD on Quantity Sold, but that came up with anything over 1 as being an outlier, which is obviously not correct since having a Quantity Sold of 1 only puts us in the 54th percentile.  Even having a Quantity Sold of 2 only puts us in the 77th percentile.  If we set outliers as anything over 1 Quantity Sold as the MCD recommended, it would basically cut the data in half with 613K outliers and 739K Inliers.  As a result (and to be consistent with methods used), I did not remove any outliers in terms of Quantity Sold.

I tried running regression models on those subsets but it keeps crashing my laptop.  Even just running the code chunk above takes my laptop 20 minutes to run.  Someone with a better machine can run those regression models to see how useful any of this is.

**Comment by Kydoimos97** [comment]
Do you think instead of cutting we can impute outliers with 5.93 dollars too? We might have to run some tests to see what the effect is. 

Next to this can you also calculate the MCD of Sales volume? It would be interesting to see since prices can vary what the threshold is there and if it allows for less imputations/removals.

**Comment by timgain** [comment]
# Outliers in Quantity Sold
```{r}

##choose explanatory variables
x.mcd=covMcd(df$Quantity_Sold, alpha=.5) ##Run MCD

# creates a new data set where 0, 1 outlier scores are in the first column (0=outlier and 1=inlier)
qty.new <- data.frame(x.mcd$mcd.wt,df)

##Subset data after removing outliers and the first column
qty.subset <- new[-which(x.mcd$mcd.wt == 0),-1 ]

sum(x.mcd$mcd.wt == 0) #counts number of outliers (613,156 outliers for Quantity Sold)
sum(x.mcd$mcd.wt == 1) # counts number of inliers (738,968 inliers for Quantity Sold)

summary(qty.subset$Quantity_Sold)  # outliers begin over Quantity_Sold > 1
IQR(qty.subset$Quantity_Sold)
str(qty.subset)
ecdf(df$Quantity_Sold)(1)  # Quantity Sold = 1 is in the 0.5465238 percentile

ggplot(qty.subset,aes(Quantity_Sold)) + geom_histogram() + labs(title="Distribution of Sales After Removing Quantity Sold Outliers", x="Sales ($)", y="Count") + scale_x_continuous(labels = comma) + scale_y_continuous(labels = comma) + theme_minimal()

ggplot(qty.subset,aes(Quantity_Sold)) + geom_boxplot()

## now run linear regression without outliers
# summary(qty.subset.reg <- lm(Sales~., data = qty.subset))  # can't run vector of 4.2 GB
```

**Comment by timgain** [comment]
As I mentioned above, I don't feel as confident with the MCD from Quantity Sold as I do for Sales.  The numbers just don't make sense this time.

By imputing the 5.93 into the rest of the dataset, do you mean overwriting the outliers above Sales=5.93 to just be 5.93 instead of whatever they were previously/actually?  That would obviously cause false data in the Quantity Sold variable as well.  We still have 1.1M rows of data (83% of the initial dataset) which should be sufficient to generate useful models.  Was there something you were hoping to see?  Or did I just misunderstand what you are looking for?

**Comment by Kydoimos97** [comment]
What package are you using Tim? I'd like to run a looped alpha and see outcomes, using alpha 0.9 with a larger subset might help to get deeper into that long right tail.

**Comment by Kydoimos97** [comment]
> Was there something you were hoping to see? Or did I just misunderstand what you are looking for?

I was hoping that we would not have to discard this much data. I sounds like it's almost nothing but it leaves gaps in our timeseries with can have quite the effect. If we didn't run timeseries I'd agree with you this is fine. But a lot of these inputs do not seem to be mistakes or out of the ordinary since 17% of the data falls outside our calculated bounds. I think we would have to subject our threshold to reality more then we do now. I bet this method would work wonders on a gaussian distribution but due to the extreme skew we have we might have to transform first and then run this?

**Comment by timgain** [comment]
library(tidyverse)
library(ggplot2)
library(caret)
library(robustbase)
library(chemometrics)
library(scales)
library(dplyr)

Makes sense.  I can work on that a little more tomorrow night as well.  For comparison, you can calculate quantiles at various thresholds below:

quantile(df$Sales,probs = c(0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95))

Just change the amounts to whatever percentile you would like to see.  If you wanted to run it at the 90th percentile, etc, this will tell you what that Sales amount would be to get to that percentile.

**Comment by Kydoimos97** [comment]
Normalization Package: [https://cran.r-project.org/web/packages/bestNormalize/vignettes/bestNormalize.html](https://cran.r-project.org/web/packages/bestNormalize/vignettes/bestNormalize.html)

Remove everything only retain quantity_sold and sales, and possibly price made with
df$price <- df$sales / df$quantity_sold
```
```{r, eval=T}
# Normalization of target variable
skewness(userprofile$paid_files)

skewnessDF <- data.frame(Variables=character(length(c(names(select_if(userprofile, is.numeric))))),
                 Skewness=as.numeric(8))
skewnessDF$Skewness <-  colskewness(as.matrix(select_if(userprofile, is.numeric)))
skewnessDF$Variables <- names(select_if(userprofile, is.numeric))
(skewnessDF <- skewnessDF[order(abs(skewnessDF$Skewness), decreasing = TRUE),])

skewed_values <- skewnessDF$Variables[abs(skewnessDF$Skewness) > 0.75]

for (i in skewed_values){
  x_trans <- bestNormalize(userprofile[[i]], out_of_sample = FALSE, allow_orderNorm = FALSE)
  userprofile[[i]] <- x_trans$x.t
  print(i)
  print(x_trans$chosen_transform)
}

skewnessDF <- data.frame(Variables=character(length(c(names(select_if(userprofile, is.numeric))))),
                 Skewness=as.numeric(8))
skewnessDF$Skewness <-  colskewness(as.matrix(select_if(userprofile, is.numeric)))
skewnessDF$Variables <- names(select_if(userprofile, is.numeric))
(skewnessDF <- skewnessDF[order(abs(skewnessDF$Skewness), decreasing = TRUE),])

rm(x_trans, i, skewed_values, skewnessDF)


userprofile <- as.data.frame(lapply(userprofile, function (x) if (is.factor(x)) factor(x) else x))
```

**Comment by timgain** [comment]
Would doing something like SVR instead of linear regression be helpful?  My understanding is SVR doesn't really care about outliers and is intended to work with regression models that aren't necessarily linear.  It might take a while to run a trained model with this much data, but would it provide better prediction results?  In my prior classes, SVR has usually been better at prediction than linear regression has, particularly when adjusting the various parameters like cost, gamma, and kernal type.  Thoughts?

**Comment by Kydoimos97** [comment]
I'd say we can always try that after we have our linear regression working. Speed if you have to run something every 10days/2weeks is certainly something to consider. I think the previously outlined approach is a good baseline and SVR a possibility at the end of the process. I am also not sure how long the grid searching will take and if we can even run the matrix with the machines we got.

**Comment by timgain** [comment]
# Sales Outliers based on IQR
```{r}
# determine Inter Quartile Range
quantile(df$Sales)
quantile(df$Sales, probs = 0.25) - 1.5*iqr(df$Sales)  # means low outliers start at sales < -2.68 which is not possible
quantile(df$Sales, probs = 0.75) + 1.5*iqr(df$Sales)  # means high outliers start at sales > 9.24

# determine percentile of the Sales cutoff point
ecdf(df$Sales)(9.24)  # 93.8 percentile

# take subset of data to exclude the outliers
sales_1.5_iqr <- subset(df, df$Sales <= 9.24)

# see size of reduced dataset excluding outliers
nrow(df)  # full dataset contains 1,352,124 observations
nrow(sales_1.5_iqr)  # after removing outliers, dataset now contains 1,268,417 observations (removed 83,707 observations)

# comparing Sales boxplots on full data to reduced dataset after removing outliers
ggplot(df,aes(Sales)) + geom_boxplot() + scale_x_continuous(labels=comma) + coord_flip() + theme_classic() + labs(title = "Boxplot of Sales Before Removing Sales Outliers")
ggplot(sales_1.5_iqr,aes(Sales)) + geom_boxplot() + scale_x_continuous(labels=comma) + coord_flip() + theme_classic() + labs(title = "Boxplot of Sales After Removing Sales Outliers")

# comparing histograms of original data to the reduced set excluding outliers
ggplot(df,aes(Sales)) + geom_histogram(bins = 150) + theme_classic() + labs(title = "Distribution of Sales Before Removing Sales Outliers")
ggplot(sales_1.5_iqr,aes(Sales)) + geom_histogram(bins = 150) + theme_classic() + labs(title = "Distribution of Sales After Removing Sales Outliers")

# compare quartiles, mean, and standard deviation of original dataset to those of the reduced dataset excluding outliers
# impact on Sales after removing Sales outliers
summary(df$Sales)
sd(df$Sales)
summary(sales_1.5_iqr$Sales)
sd(sales_1.5_iqr$Sales)

# impact on Quantity Sold after removing Sales outliers
summary(df$Quantity_Sold)
sd(df$Quantity_Sold)
summary(sales_1.5_iqr$Quantity_Sold)
sd(sales_1.5_iqr$Quantity_Sold)
```

**Comment by timgain** [comment]
# Quantity Sold outliers based on IQR
```{r}
# determine Inter Quartile Range
quantile(df$Quantity_Sold)
quantile(df$Quantity_Sold, probs = 0.25) - 1.5*iqr(df$Quantity_Sold)  # means low outliers start at quantity sold < -0.5 which is not possible
quantile(df$Quantity_Sold, probs = 0.75) + 1.5*iqr(df$Quantity_Sold)  # means high outliers start at quantity sold > 3.5

# determine percentile of the Sales cutoff point
ecdf(df$Quantity_Sold)(3.5)  # 87.4 percentile

# take subset of data to exclude the outliers
qty_sold_1.5_iqr <- subset(df, df$Quantity_Sold <= 3.5)

# see size of reduced dataset excluding outliers
nrow(df)  # full dataset contains 1,352,124 observations
nrow(qty_sold_1.5_iqr)  # after removing outliers, dataset now contains 1,182,177 observations (removed 169,947 rows)

# comparing boxplots of Quantity Sold on full dataset versus after removing Quantity Sold outliers
ggplot(df,aes(Quantity_Sold)) + geom_boxplot() + scale_x_continuous(labels=comma) + coord_flip() + theme_classic() + labs(title = "Boxplot of Quantity Sold Before Removing Quantity Sold Outliers")
ggplot(qty_sold_1.5_iqr,aes(Quantity_Sold)) + geom_boxplot() + scale_x_continuous(labels=comma) + coord_flip() + theme_classic() + labs(title = "Boxplot of Quantity Sold After Removing Quantity Sold Outliers")

# comparing histograms of original data to the reduced set excluding outliers
ggplot(df,aes(Quantity_Sold)) + geom_histogram() + scale_x_continuous(labels=comma) + theme_classic() + labs(title = "Distribution of Quantity Sold Before Removing Quantity Sold Outliers")
ggplot(qty_sold_1.5_iqr,aes(Quantity_Sold)) + geom_histogram() + scale_x_continuous(labels=comma) + theme_classic() + labs(title = "Distribution of Quantity Sold After Removing Quantity Sold Outliers")

# compare quartiles, mean, and standard deviation of original dataset to those of the reduced dataset excluding outliers
# impact on Sales after removing Quantity Sold outliers
summary(df$Sales)
sd(df$Sales)
summary(qty_sold_1.5_iqr$Sales)
sd(qty_sold_1.5_iqr$Quantity_Sales)

# impact on Quantity Sold after removing Quantity Sold outliers
summary(df$Quantity_Sold)
sd(df$Quantity_Sold)
summary(qty_sold_1.5_iqr$Quantity_Sold)
sd(qty_sold_1.5_iqr$Quantity_Sold)
```

**Comment by timgain** [comment]
I tried using the bestNormalize package info you sent and was able to normalize the data, but I still haven't figured out how to get it back into standard units to actually make it useful afterwards.  Even though the data is skewed, I looked at the data based on a more common outlier detector of 1.5*IQR to see what that would look like in skewed data.  The lower-bound outliers don't make sense (having negative sales or negative quantity sold) but the upper-bound outliers could make sense.  Using 1.5*IQR gives an upper Sales outlier limit of 9.24 which is almost in the 94th percentile.  We only eliminated 83,707 high-end outliers using this method (still keeping almost 1.3M rows).

When applying the same methodology to Quantity Sold, it comes up with outliers being Quantity_Sold > 3.5.  Obviously we wouldn't sell half of a candy bar, so it is really anything over 3 would be an outlier for quantity sold.  This method removes about 170k outliers and is in the 87th percentile.

These are much more realistic than the methods used earlier with MCD.  There are much fewer data points removed this way.  This is also helpful since many websites I have read seem to indicate that outliers should not be removed unless they are obvious errors.  Some of the most extreme could very well be typos, but some lower-level outliers may be accurate and so we might want to leave them in the data for our analysis.

**Comment by Kydoimos97** [comment]
![image](https://user-images.githubusercontent.com/63725110/111694290-53f26b00-87f7-11eb-85e9-c54660570ca3.png)
![image](https://user-images.githubusercontent.com/63725110/111694302-5654c500-87f7-11eb-973b-019a985ccd10.png)
![image](https://user-images.githubusercontent.com/63725110/111694310-58b71f00-87f7-11eb-8a55-91e6adc1cd50.png)

**Comment by Kydoimos97** [comment]
I closed this issue to it being resolved. Refer to issue #31 for further information

@timgain Thank you for the insights they were very useful. Refer to the [this](https://github.com/Kydoimos97/CapstoneMSBA2020/blob/main/PythonCode/DataCleaning/Python_CleaningPDF.pdf) file so you understand the process and we can discuss it tomorrow.
