### ISSUE TITLE
Maverik EDA Feedback

### ISSUE THREAD

**Issue by kelsey-codes** [Kydoimos97/CapstoneMSBA2020#29]
1. Regarding your work on sales outliers, I remember mentioning that outliers would need to be systematically dealt with given that sales data is live and audits aren’t performed until period end. I might have mentioned it only to the other team though. If I did, my apologies.

2. I understand your concerns regarding temperature. It’s difficult considering you don’t have any lat/long information. I would recommend you impute like you mentioned in your analysis.

3. Your note on singularities is accurate, but really important. Having a site down for a project and come back up affects the patterns significantly. You might consider focusing your model on sites without projects (since the data set is so imbalanced int that regard) and use an alternative method for projecting sales at sites with projects.

4. I would consider leveraging the location id variables more, and perhaps limiting your main model to only when a site has been on board for some period of time. The best indicator of a site’s sales are it’s sales last week, last year, and yesterday.

**Comment by Kydoimos97** [comment]
1. We will set a statistically backed upper range, IQR might not work due to the mean being only 3, but based on training data we can set a confidence range of 95%. 

3. Good suggestion, I won't take this into account when I'll code for this week but we should explore this. 

4. This I will try to take into account for this week as this relaxation of possible scenarios can help us a lot.
